export const contractABI = [
  {
    inputs: [],
    name: "nextAgreementId",
    outputs: [{ internalType: "uint256", name: "", type: "uint256" }],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [{ internalType: "uint256", name: "_agreementId", type: "uint256" }],
    name: "getAgreement",
    outputs: [
      {
        components: [
          { internalType: "uint256", name: "agreementId", type: "uint256" },
          { internalType: "uint256", name: "gpuId", type: "uint256" },
          { internalType: "address payable", name: "renter", type: "address" },
          { internalType: "uint256", name: "startTime", type: "uint256" },
          { internalType: "uint256", name: "escrowFund", type: "uint256" },
          { internalType: "bool", name: "isActive", type: "bool" },
        ],
        internalType: "struct GPURentalPlatform.RentalAgreement",
        name: "",
        type: "tuple",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [],
    name: "getAllGPUs",
    outputs: [
      {
        components: [
          { internalType: "uint256", name: "gpuId", type: "uint256" },
          { internalType: "address payable", name: "owner", type: "address" },
          { internalType: "string", name: "hardwareSpec", type: "string" },
          { internalType: "string", name: "hardwareSpecHash", type: "string" },
          { internalType: "string", name: "metadataCID", type: "string" },
          { internalType: "uint256", name: "pricePerHour", type: "uint256" },
          { internalType: "uint256", name: "minStakingRequired", type: "uint256" },
          { internalType: "enum GPURentalPlatform.GPUStatus", name: "status", type: "uint8" },
        ],
        internalType: "struct GPURentalPlatform.GPU[]",
        name: "",
        type: "tuple[]",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [{ internalType: "uint256", name: "gpuId", type: "uint256" }],
    name: "startRental",
    outputs: [],
    stateMutability: "payable",
    type: "function",
  },
  {
    inputs: [
      { internalType: "string", name: "_spec", type: "string" },
      { internalType: "string", name: "_metadataCID", type: "string" },
      { internalType: "uint256", name: "_pricePerHour", type: "uint256" },
    ],
    name: "registerGPUWithCID",
    outputs: [],
    stateMutability: "payable",
    type: "function",
  },
  {
    anonymous: false,
    inputs: [
      { indexed: true, internalType: "uint256", name: "agreementId", type: "uint256" },
      { indexed: true, internalType: "uint256", name: "gpuId", type: "uint256" },
      { indexed: true, internalType: "address", name: "renter", type: "address" },
      { indexed: false, internalType: "address", name: "owner", type: "address" },
      { indexed: false, internalType: "uint256", name: "startTime", type: "uint256" },
      { indexed: false, internalType: "uint256", name: "escrowFund", type: "uint256" },
    ],
    name: "RentalStarted",
    type: "event",
  },
  {
    inputs: [{ internalType: "address", name: "provider", type: "address" }],
    name: "getProviderBalance",
    outputs: [{ internalType: "uint256", name: "", type: "uint256" }],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [{ internalType: "address", name: "", type: "address" }],
    name: "providerBalances",
    outputs: [{ internalType: "uint256", name: "", type: "uint256" }],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [],
    name: "getPlatformBalance",
    outputs: [{ internalType: "uint256", name: "", type: "uint256" }],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [],
    name: "withdrawProviderEarnings",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [],
    name: "withdrawPlatformFees",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [
      { internalType: "uint256", name: "_agreementId", type: "uint256" },
      { internalType: "string", name: "_telemetryHash", type: "string" },
    ],
    name: "endRentalSession",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
] as const;
